config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens

end

app/models/kitten.rb
class Kitten < ActiveRecord::Base
	validates :name, presence: true
	validates :age, presence: true
	validates :cuteness, presence: true
	validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
	before_action :dropdown_values, only: [:new, :edit]
	before_action :find_kitten, only: [:show, :edit, :update, :destroy]

	def index
		@kittens = Kitten.all

		respond_to do |format|
			format.html { render }
			format.json { render :json => @kittens }
		end
	end

	def show
		respond_to do |format|
			format.html { render }
			format.json { render :json => @kitten }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = 'Kitten created!'
			redirect_to @kitten
		else
			flash.now[:error] = 'Error! Kitten not saved!'
			render 'new'
		end
	end

	def edit
	end

	def update
		if @kitten.update_attributes(kitten_params)
			flash[:success] = 'Kitten updated!'
			redirect_to @kitten
		else
			flash.now[:error] = 'Error! Kitten not updated!'
			render 'edit'
		end
	end

	def destroy
	  @kitten.destroy
	  flash[:success] = "Kitten deleted!"
	  redirect_to root_path
	end

	private
	def kitten_params
		params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	end

	def dropdown_values
		@cuteness = [
								 ['Scares the Children', 1], ['Meh', 2], ['Cute', 3], 
		             ['Really Cute', 4], ['Extremely Cute', 5]
		            ]
		@softness = [
			           ['Like Sandpaper', 1], ['Meh', 2], ['Soft', 3], 
								 ['Really Soft', 4], ['Like Hugging a Cloud', 5]
								]
	end

	def find_kitten
		begin
			@kitten = Kitten.find(params[:id])
		rescue	
			flash[:error] = "Sorry, that kitten doesn't exist!"
			redirect_to root_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<section>
	<h3><%= kitten.name %></h3>

	<ul>
		<li>Age: <%= kitten.age %></li>
		<li>Cuteness: <%= kitten.cuteness %></li>
		<li>Softness: <%= kitten.softness %></li>
		<li><%= link_to "View Profile", kitten %></li>
		<li><%= link_to "Delete", kitten, method: :delete %></li>
	</ul>
<section>

app/views/kittens/_kitten_form.html.erb
<%= form_for @kitten do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :age %>
	<%= f.number_field :age, in: 0.5..50, step: 0.5 %>
	<br>
	<%= f.label :cuteness %>
	<%= f.select(:cuteness, @cuteness, prompt: "How Cute?") %>
	<br>
	<%= f.label :softness %>
	<%= f.select(:softness, @softness, prompt: "How Soft?") %>
	<br>
	<%= f.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit a Kitten</h1>
<%= render 'kitten_form' %>
<%= link_to "Delete Kitten", @kitten, method: :delete %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>
<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>Add a New Kitten</h1>
<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<h1>Profile Page for <%= @kitten.name %></h1>
<%= render @kitten %>
<%= link_to "Edit Kitten", edit_kitten_path(@kitten) %>
<%= link_to "Delete Kitten", @kitten, method: :delete %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
	<%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KittensApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash.any? %>
	<%= render 'layouts/flash' %>
	<br>
<% end %>

<%= link_to "Home", root_path %>
<%= link_to "Create a Kitten", new_kitten_path %>

<%= yield %>

<%= debug(params) if Rails.env.development? %>
</body>
</html>